from .model import *
from .segnet import *
from .quicknat import *
from .probabilistic_quicknat import *
from .resultnet import *
from .simplenet import *
from .quickresnet import *
from .quickfcn import *
from .quickfcn_classifier import *
from .softquickfcn import *
from .custom_quicknat import *
